### PR TITLE
buddy

### PR DESCRIPTION
**Pull request by myffs**
im back,you want some help?

### CODE REVIEW

**Comment by WarlyFarly-Github** [comment]
hello and yes i need help
idk how to code
so when i have ideas i will tell you

**Comment by myffs** [comment]
> hello and yes i need help idk how to code so when i have ideas i will tell you

are they gonna be haxe files?

im kinda pretty good at haxe

**Comment by myffs** [comment]
> > hello and yes i need help idk how to code so when i have ideas i will tell you
> 
> are they gonna be haxe files?
> 
> im kinda pretty good at haxe

but not lua 💀

**Comment by myffs** [comment]
im bored asf rn so please give me a idea

**Comment by WarlyFarly-Github** [comment]
bad news. i have to make it compatible for MacOs and Windows, so no hx ): i only have hx in because it's a copy of psych

**Comment by myffs** [comment]
> bad news. i have to make it compatible for MacOs and Windows, so no hx ): i only have hx in because it's a copy of psych

ooooh ok,so only lua then?

**Comment by WarlyFarly-Github** [comment]
i'm also trying to make it the first engine that works mostly on lua

**Comment by WarlyFarly-Github** [comment]
yes, only lua

**Comment by WarlyFarly-Github** [comment]
hold on, i'll give you admin

**Comment by WarlyFarly-Github** [comment]
ok sent the invite

**Comment by myffs** [comment]
> ok sent the invite

ok thx

**Comment by myffs** [comment]
> i'm also trying to make it the first engine that works mostly on lua

there are lots of other engines that work only on lua

**Comment by WarlyFarly-Github** [comment]
> > i'm also trying to make it the first engine that works mostly on lua
> 
> there are lots of other engines that work only on lua

oh yea
then i'll be one of them

**Comment by myffs** [comment]
> > > i'm also trying to make it the first engine that works mostly on lua
> > 
> > 
> > there are lots of other engines that work only on lua
> 
> oh yea then i'll be one of them

lmfao, ok

**Comment by WarlyFarly-Github** [comment]
> > > > i'm also trying to make it the first engine that works mostly on lua
> > > 
> > > 
> > > there are lots of other engines that work only on lua
> > 
> > 
> > oh yea then i'll be one of them
> 
> lmfao, ok

yea ok

**Comment by WarlyFarly-Github** [comment]
also i gave you a gamebanana permit
https://gamebanana.com/tools/11331

**Comment by myffs** [comment]
> also i gave you a gamebanana permit https://gamebanana.com/tools/11331

tysm <333

**Comment by WarlyFarly-Github** [comment]
i need help on my mod. it's called u-sides. it has been withheld and i need you to create a remix of bopeebo

**Comment by myffs** [comment]
> i need help on my mod. it's called u-sides. it has been withheld and i need you to create a remix of bopeebo

BETT!!! i GOT FL STUDIO

**Comment by WarlyFarly-Github** [comment]
> > i need help on my mod. it's called u-sides. it has been withheld and i need you to create a remix of bopeebo
> 
> BETT!!! i GOT FL STUDIO

WAHOO! gotta make it fast though, it got withheld cause i had nothin' to show.

**Comment by WarlyFarly-Github** [comment]
look at the readme for you

i need you

**Pull request closed without merging**
